"""update user category to type enum in users table

Revision ID: b35ec9eb0706
Revises: 4e39c7a2275f
Create Date: 2024-11-04 14:27:56.768793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b35ec9eb0706'
down_revision: Union[str, None] = '4e39c7a2275f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # execute command to create type category in postgresql db
    op.execute("CREATE TYPE category AS ENUM ('FUNNY', 'HAPPY', 'SAD', 'ANGRY', 'OTHER')")

    # execute command to change quotes db type to 'category'
    op.execute("ALTER TABLE quotes ALTER COLUMN category TYPE category USING category::category")

    op.alter_column('quotes', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # execute command to change quotes db type to 'category'
    op.execute("ALTER TABLE quotes ALTER COLUMN category TYPE VARCHAR()")

    # execute command to drop type category
    op.execute("DROP TYPE category")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
