[alembic]
script_location = migrations

prepend_sys_path = .

# timezone =
# truncate_slug_length = 40
# revision_environment = false
# sourceless = false
# version_locations = %(here)s/bar:%(here)s/bat:migrations/versions
# version_path_separator = :
# version_path_separator = ;
# version_path_separator = space
# version_path_separator = newline

version_path_separator = os  # Use os.pathsep. Default configuration used for new projects.

# recursive_version_locations = false
# output_encoding = utf-8

sqlalchemy.url = os.getenv("DB_URL")

# post write hooks
[post_write_hooks]

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
