[tool.poetry]
name = "bubster-backend"
version = "0.3.0"
description = ""
authors = ["woodFordR <adam@kaewell.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.31.1"
fastapi = "^0.115.2"
pydantic-settings = "^2.5.2"
asyncpg = "^0.29.0"
httpx = "^0.27.2"
asgi-lifespan = "^2.1.0"
logfire = {extras = ["fastapi"], version = "^1.3.0"}
sqlmodel = "^0.0.22"
psycopg2-binary = "^2.9.10"
alembic = "^1.13.3"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.36"}
argon2-cffi = "^23.1.0"
pydantic = {extras = ["email"], version = "^2.9.2"}
pytest-cov = "^6.0.0"
trio = "^0.27.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[tool.poetry.plugins.dotenv]
ignore = "false"
location = ".test.env"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

